### ISSUE TITLE
Linux下无法使用，即使是编码全为UTF-8

### ISSUE THREAD

**Issue by MoeShimaKaze** [tocmic/deathPunishment#5]
服务端：CatServer，已在Windows端上测试可用，换到Centos上无法载入
[23:53:41] [Server thread/INFO]: [deathPunishment] Enabling deathPunishment v1.1
[23:53:41] [Server thread/INFO]: [deathPunishment] Vault运行正常！已启用经济相关功能
[23:53:41] [Server thread/INFO]: [deathPunishment] 配置文件版本:1.2
[23:53:41] [Server thread/INFO]: [deathPunishment] 数据文件plugins/deathPunishment\log.bin已挂载
[23:53:41] [Server thread/ERROR]: Error occurred while enabling deathPunishment v1.1 (Is it up to date?)
java.lang.NullPointerException: null
        at com.nflsedition.deathPunishment.dpFile.loadLangs(dpFile.java:101) ~[?:?]
        at com.nflsedition.deathPunishment.deathPunishment.onEnable(deathPunishment.java:113) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-CatServer-1.12.2-c0537be]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-c0537be]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-CatServer-1.12.2-c0537be]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:436) [CraftServer.class:git-CatServer-1.12.2-c0537be]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:384) [CraftServer.class:git-CatServer-1.12.2-c0537be]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:383) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:634) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]

**Comment by 623667595** [comment]
看来作者跑路不修了
